class Autogenerated {
  String accessToken;
  String tokenType;
  int expiresIn;

  Autogenerated({this.accessToken, this.tokenType, this.expiresIn});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token'];
    tokenType = json['token_type'];
    expiresIn = json['expires_in'];
  }

  @override
  String toString() {
    return 'Autogenerated{accessToken: $accessToken, tokenType: $tokenType, expiresIn: $expiresIn}';
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['access_token'] = this.accessToken;
    data['token_type'] = this.tokenType;
    data['expires_in'] = this.expiresIn;
    return data;
  }
}